lapActiverAtcdStrucSur: 'atcdObs,atcdPersoGyneco,atcdMedicChir'
lapActiverAllergiesStrucSur: 'allergies'
lapAtcdStrucPersoPourAnalyse: 'atcdObs,atcdPersoGyneco,atcdMedicChir'
lapAllergiesStrucPersoPourAnalyse: 'allergies'
